### ISSUE TITLE
Error handling for Network Unreachable

### ISSUE THREAD

**Issue by shader** [zeromq/pyre#72] opened 2015-05-13 18:16 UTC
If the network goes down for some reason, zbeacon produces the following error message:

    Traceback (most recent call last):
      File "/usr/lib64/python2.7/threading.py", line 810, in __bootstrap_inner
        self.run()
      File "/usr/lib64/python2.7/threading.py", line 763, in run
        self.__target(*self.__args, **self.__kwargs)
      File "/usr/lib64/python2.7/site-packages/pyre/zbeacon.py", line 204, in __init__
        self.run()
      File "/usr/lib64/python2.7/site-packages/pyre/zbeacon.py", line 398, in run
        self.send()
      File "/usr/lib64/python2.7/site-packages/pyre/zbeacon.py", line 338, in send
        self._udp_sock.sendto(self.transmit, (str(self.announce_address), self._port))
    error: [Errno 101] Network is unreachable

What is the proper way to provide error handling for this situation? I'd like to implement something like sleep + retry, but I could imagine others wanting to provide a different handler.

**Comment by sphaero** [comment] 2015-05-14 06:39
I'm not sure yet what is best. Best is to close the socket and try to open a new one. Or close the zbeacon instance and create a new one. Best is to mimic behaviour of zyre?

**Comment by shader** [comment] 2015-05-14 14:03
Where is the right place to catch the exception, since it's occurring on a different thread?

**Comment by sphaero** [comment] 2015-05-22 13:09
At the send. Usually you get the exception when you try to do a send. This is where you'd need to intervene

**Comment by sphaero** [comment] 2015-05-22 13:10
duplicate of #1, please add comments there

**Closed by sphaero** 2015-05-22 13:10 UTC
Labels: duplicate
