### ISSUE TITLE
package broken due to last change

### ISSUE THREAD

**Issue by purplepeng8** [zeromq/pyre#112] opened 2017-05-04 12:29 UTC
`   from pyre.zactor import ZActor
  File "/Users/.../development/work/.venv/lib/python2.7/site-packages/pyre/__init__.py", line 6, in <module>
    with open(version_file_path) as version_file:
IOError: [Errno 2] No such file or directory: '/Users/.../development/work/.venv/lib/python2.7/site-packages/pyre/VERSION'
`

**Comment by bluca** [comment] 2017-05-04 12:35
Should be fixed by https://github.com/zeromq/pyre/pull/111

**Comment by purplepeng8** [comment] 2017-05-04 12:39
Fix does not work, still broken

**Comment by bluca** [comment] 2017-05-04 12:46
@papr could you please have a look?

**Comment by papr** [comment] 2017-05-04 13:08
I was able to reproduce the error with a fresh python 2.7 venv. Not sure what the issue is.

**Comment by purplepeng8** [comment] 2017-05-04 13:11
I think version file is missing in MANIFEST.in

**Comment by papr** [comment] 2017-05-04 13:23
Just adding it to MANIFEST does not fix it. Following this should be the correct way to solve this issue:
http://stackoverflow.com/questions/1395593/managing-resources-in-a-python-project

**Comment by papr** [comment] 2017-05-04 13:44
Ok, I found a solution. Should be fixed with #113.
Apologies, that this took three PRs. Apparently,  installing using `python setup.py install` is different than installing with `pip`...

**Comment by papr** [comment] 2017-05-04 13:46
@purplepeng8 Can you confirm that the fix works?

**Closed** 2017-05-04 13:49 UTC

**Comment by purplepeng8** [comment] 2017-05-04 13:52
Looks good, thanks
