### ISSUE TITLE
Is Pyre working on ARM architecture?

### ISSUE THREAD

**Issue by WestFlame** [zeromq/pyre#107] opened 2017-01-19 09:48 UTC
I'm trying to run Pyre based application on ARM (Jetson TX1) and getting the following error. The same code runs on x64 processor fine. Does anybody have idea what is causing this?

```python
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/.virtualenvs/sidas/lib/python3.5/site-packages/pyre/zactor.py", line 57, in run
    self.shim_handler(*self.shim_args, **self.shim_kwargs)
  File "/home/ubuntu/.virtualenvs/sidas/lib/python3.5/site-packages/pyre/zbeacon.py", line 64, in __init__
    self.run()
  File "/home/ubuntu/.virtualenvs/sidas/lib/python3.5/site-packages/pyre/zbeacon.py", line 287, in run
    self.handle_pipe()
  File "/home/ubuntu/.virtualenvs/sidas/lib/python3.5/site-packages/pyre/zbeacon.py", line 216, in handle_pipe
    self.configure(port)
  File "/home/ubuntu/.virtualenvs/sidas/lib/python3.5/site-packages/pyre/zbeacon.py", line 199, in configure
    self.prepare_udp()
  File "/home/ubuntu/.virtualenvs/sidas/lib/python3.5/site-packages/pyre/zbeacon.py", line 71, in prepare_udp
    self._prepare_socket()
  File "/home/ubuntu/.virtualenvs/sidas/lib/python3.5/site-packages/pyre/zbeacon.py", line 135, in _prepare_socket
    netinf = zhelper.get_ifaddrs()
  File "/home/ubuntu/.virtualenvs/sidas/lib/python3.5/site-packages/pyre/zhelper.py", line 291, in get_ifaddrs
    total += si.sll_addr[i]
IndexError: invalid index
```

**Comment by wesyoung** [comment] 2017-01-19 12:37
that function relies heavily on some C based libs:

https://github.com/zeromq/pyre/blob/master/pyre/zhelper.py#L95

my guess is if you `pprint` around in that function, you'll see either there are zero adapters being found, or different adapters than the function was expecting...

**Comment by sphaero** [comment] 2017-01-20 13:23
apparently the get_ifaddrs() method doesn't work on your platform.

Can you run that method directly? ie:
```
>>> from pyre import zhelper
>>> zhelper.get_ifaddrs()
[{'enp0s25': {17: {'addr': '00:21:cc:c1:5c:14'}}}, {'wlp3s0': {17: {'addr': '8c:70:5a:48:5c:f4'}, 2: {'netmask': '255.255.255.0', 'broadcast': '192.168.12.255', 'addr': '192.168.12.29'}, 10: {'netmask': 'ffff:ffff:ffff:ffff::', 'addr': 'fe80::d096:baae:16c1:299a', 'scope': 4}}}, {'wwp0s20u4i6': {17: {'addr': '02:15:e0:ec:01:00'}}}, {'lo': {2: {'netmask': '255.0.0.0', 'addr': '127.0.0.1'}, 10: {'netmask': 'ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff', 'addr': '::1'}}}]
```
It should return the network interfaces.

**Comment by WestFlame** [comment] 2017-01-24 12:33
No, it ends with similar error:

```python
>>> from pyre import zhelper
>>> zhelper.get_ifaddrs()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.virtualenvs/sidas/lib/python3.5/site-packages/pyre/zhelper.py", line 291, in get_ifaddrs
    total += si.sll_addr[i]
IndexError: invalid index
```

**Comment by sphaero** [comment] 2017-01-28 10:35
I think I'd need that machine to workout what's different. Can't tell like this

**Comment by LucaCerina** [comment] 2017-08-25 12:46
I've run it seamlessly both on an ARM Cortex A9 board and on a Raspberry Pi3, both running Ubuntu 16.04 distro. 

I am guessing it could be caused by the way the Jetson handles networking interfaces, but I never used it.

**Comment by sphaero** [comment] 2018-02-05 14:32
Since we never heard from this error again I'm closing it

**Closed by sphaero** 2018-02-05 14:32 UTC

**Comment by offby1** [comment] 2023-01-29 03:12
I've reproduced this in docker on an M1 mac.

```
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro17,1
  Model Number:	MYD82LL/A
  Chip:	Apple M1
```

Here's the Dockerfile:
```
FROM ubuntu:focal
RUN DEBIAN_FRONTEND=noninteractive apt update
RUN DEBIAN_FRONTEND=noninteractive apt install -y python3-pip
RUN python3 -m pip install https://github.com/zeromq/pyre/archive/master.zip
RUN python3 -c 'from pyre import zhelper ; print(zhelper.get_ifaddrs())'
```

I build it by simply doing `docker build .`
